name: Push the Docker image to AWS ECR Repo
on:
  push:
    branches:
      - deploy-prod
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get commit hash
        id: get-commit-hash
        run: echo "::set-output name=commit-hash::$(git rev-parse --short HEAD)"
      - name: Get timestamp
        id: get-timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y-%m-%d-%H-%M')"

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: 457789409683.dkr.ecr.ap-southeast-1.amazonaws.com
          ECR_REPOSITORY: sreweb-prod-ecr-fe
          IMAGE_TAG: latest # ${{ steps.get-commit-hash.outputs.commit-hash }}-${{ steps.get-timestamp.outputs.timestamp }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image-tag::$IMAGE_TAG"

      - name: Update ECS Task definition
        id: task-def
        uses: pooriaghaedi/amazon-ecs-deploy-task-definition@v1.0.1
        env:
          ECS_TASK_DEFINITION: sreweb-prod-ecs-tdf-fe
          REGION: ap-southeast-1
          IMAGE_URI: 457789409683.dkr.ecr.ap-southeast-1.amazonaws.com/sreweb-prod-ecr-fe:${{ steps.build-image.outputs.image-tag }}
          ECS_CLUSTER: sreweb-prod-ecs-cls-fe
          ECS_SERVICE: sreweb-prod-ecs-svc-fe
