import Header from "./components/header/page";
import Footer from "./components/footer/page";
import "./globals.css";
import "./fonts/f1/stylesheet.css";
import "./fonts/f2/stylesheet.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header backgroundImage={"/residential/header-bg.svg"}></Header>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
